/** Names companies use on X. Shown first, before census titles. */
export const companyIndustries = [
  "Tech",
  "AI",
  "Beauty",
  "Advertising",
  "Automotive",
  "Banking",
  "Biotech",
  "Clean energy",
  "Climate",
  "Cloud",
  "Consumer electronics",
  "Consumer goods",
  "Creator tools",
  "Crypto",
  "Cybersecurity",
  "Dating",
  "Defense",
  "Delivery",
  "Developer tools",
  "E-commerce",
  "Edtech",
  "Education",
  "Electric vehicles",
  "Entertainment",
  "Fashion",
  "Fintech",
  "Fitness",
  "Food and beverage",
  "Gaming",
  "Hardware",
  "Healthtech",
  "Home",
  "Hospitality",
  "Insurance",
  "Logistics",
  "Luxury",
  "Marketplaces",
  "Marketing",
  "Media",
  "Music",
  "News",
  "Payments",
  "Pets",
  "Pharma",
  "Real estate",
  "Restaurants",
  "Robotics",
  "SaaS",
  "Semiconductors",
  "Skincare",
  "Social media",
  "Software",
  "Space",
  "Sports",
  "Streaming",
  "Telecom",
  "Travel",
  "Voice AI",
  "Wellness",
] as const;

/** NAICS 2022 titles used for US industry type-ahead. */
export const usIndustries = [
  "Agriculture, Forestry, Fishing and Hunting",
  "Oilseed and Grain Farming",
  "Vegetable and Melon Farming",
  "Fruit and Tree Nut Farming",
  "Greenhouse, Nursery, and Floriculture Production",
  "Other Crop Farming",
  "Cattle Ranching and Farming",
  "Hog and Pig Farming",
  "Poultry and Egg Production",
  "Sheep and Goat Farming",
  "Aquaculture",
  "Other Animal Production",
  "Timber Tract Operations",
  "Forest Nurseries and Gathering of Forest Products",
  "Logging",
  "Fishing",
  "Hunting and Trapping",
  "Support Activities for Crop Production",
  "Support Activities for Animal Production",
  "Support Activities for Forestry",
  "Mining, Quarrying, and Oil and Gas Extraction",
  "Oil and Gas Extraction",
  "Coal Mining",
  "Iron Ore Mining",
  "Gold Ore and Silver Ore Mining",
  "Copper, Nickel, Lead, and Zinc Mining",
  "Other Metal Ore Mining",
  "Stone Mining and Quarrying",
  "Sand, Gravel, Clay, and Ceramic and Refractory Minerals Mining",
  "Other Nonmetallic Mineral Mining and Quarrying",
  "Support Activities for Mining",
  "Utilities",
  "Electric Power Generation",
  "Electric Power Transmission, Control, and Distribution",
  "Natural Gas Distribution",
  "Water, Sewage and Other Systems",
  "Construction",
  "Residential Building Construction",
  "Nonresidential Building Construction",
  "Utility System Construction",
  "Land Subdivision",
  "Highway, Street, and Bridge Construction",
  "Other Heavy and Civil Engineering Construction",
  "Foundation, Structure, and Building Exterior Contractors",
  "Building Equipment Contractors",
  "Building Finishing Contractors",
  "Other Specialty Trade Contractors",
  "Manufacturing",
  "Animal Food Manufacturing",
  "Grain and Oilseed Milling",
  "Sugar and Confectionery Product Manufacturing",
  "Fruit and Vegetable Preserving and Specialty Food Manufacturing",
  "Dairy Product Manufacturing",
  "Animal Slaughtering and Processing",
  "Seafood Product Preparation and Packaging",
  "Bakeries and Tortilla Manufacturing",
  "Other Food Manufacturing",
  "Beverage Manufacturing",
  "Tobacco Manufacturing",
  "Fiber, Yarn, and Thread Mills",
  "Fabric Mills",
  "Textile and Fabric Finishing and Fabric Coating Mills",
  "Textile Furnishings Mills",
  "Other Textile Product Mills",
  "Apparel Knitting Mills",
  "Cut and Sew Apparel Manufacturing",
  "Apparel Accessories and Other Apparel Manufacturing",
  "Leather and Hide Tanning and Finishing",
  "Footwear Manufacturing",
  "Other Leather and Allied Product Manufacturing",
  "Sawmills and Wood Preservation",
  "Veneer, Plywood, and Engineered Wood Product Manufacturing",
  "Other Wood Product Manufacturing",
  "Pulp, Paper, and Paperboard Mills",
  "Converted Paper Product Manufacturing",
  "Printing and Related Support Activities",
  "Petroleum and Coal Products Manufacturing",
  "Basic Chemical Manufacturing",
  "Resin, Synthetic Rubber, and Artificial and Synthetic Fibers and Filaments Manufacturing",
  "Pesticide, Fertilizer, and Other Agricultural Chemical Manufacturing",
  "Pharmaceutical and Medicine Manufacturing",
  "Paint, Coating, and Adhesive Manufacturing",
  "Soap, Cleaning Compound, and Toilet Preparation Manufacturing",
  "Other Chemical Product and Preparation Manufacturing",
  "Plastics Product Manufacturing",
  "Rubber Product Manufacturing",
  "Clay Product and Refractory Manufacturing",
  "Glass and Glass Product Manufacturing",
  "Cement and Concrete Product Manufacturing",
  "Lime and Gypsum Product Manufacturing",
  "Other Nonmetallic Mineral Product Manufacturing",
  "Iron and Steel Mills and Ferroalloy Manufacturing",
  "Steel Product Manufacturing from Purchased Steel",
  "Alumina and Aluminum Production and Processing",
  "Nonferrous Metal (except Aluminum) Production and Processing",
  "Foundries",
  "Forging and Stamping",
  "Cutlery and Handtool Manufacturing",
  "Architectural and Structural Metals Manufacturing",
  "Boiler, Tank, and Shipping Container Manufacturing",
  "Hardware Manufacturing",
  "Spring and Wire Product Manufacturing",
  "Machine Shops; Turned Product; and Screw, Nut, and Bolt Manufacturing",
  "Coating, Engraving, Heat Treating, and Allied Activities",
  "Other Fabricated Metal Product Manufacturing",
  "Agriculture, Construction, and Mining Machinery Manufacturing",
  "Industrial Machinery Manufacturing",
  "Commercial and Service Industry Machinery Manufacturing",
  "Ventilation, Heating, Air-Conditioning, and Commercial Refrigeration Equipment Manufacturing",
  "Metalworking Machinery Manufacturing",
  "Engine, Turbine, and Power Transmission Equipment Manufacturing",
  "Other General Purpose Machinery Manufacturing",
  "Computer and Peripheral Equipment Manufacturing",
  "Communications Equipment Manufacturing",
  "Audio and Video Equipment Manufacturing",
  "Semiconductor and Other Electronic Component Manufacturing",
  "Navigational, Measuring, Electromedical, and Control Instruments Manufacturing",
  "Manufacturing and Reproducing Magnetic and Optical Media",
  "Electric Lighting Equipment Manufacturing",
  "Household Appliance Manufacturing",
  "Electrical Equipment Manufacturing",
  "Other Electrical Equipment and Component Manufacturing",
  "Motor Vehicle Manufacturing",
  "Motor Vehicle Body and Trailer Manufacturing",
  "Motor Vehicle Parts Manufacturing",
  "Aerospace Product and Parts Manufacturing",
  "Railroad Rolling Stock Manufacturing",
  "Ship and Boat Building",
  "Other Transportation Equipment Manufacturing",
  "Household and Institutional Furniture and Kitchen Cabinet Manufacturing",
  "Office Furniture (including Fixtures) Manufacturing",
  "Other Furniture Related Product Manufacturing",
  "Medical Equipment and Supplies Manufacturing",
  "Other Miscellaneous Manufacturing",
  "Wholesale Trade",
  "Motor Vehicle and Motor Vehicle Parts and Supplies Merchant Wholesalers",
  "Furniture and Home Furnishing Merchant Wholesalers",
  "Lumber and Other Construction Materials Merchant Wholesalers",
  "Professional and Commercial Equipment and Supplies Merchant Wholesalers",
  "Metal and Mineral (except Petroleum) Merchant Wholesalers",
  "Household Appliances and Electrical and Electronic Goods Merchant Wholesalers",
  "Hardware, and Plumbing and Heating Equipment and Supplies Merchant Wholesalers",
  "Machinery, Equipment, and Supplies Merchant Wholesalers",
  "Miscellaneous Durable Goods Merchant Wholesalers",
  "Paper and Paper Product Merchant Wholesalers",
  "Drugs and Druggists' Sundries Merchant Wholesalers",
  "Apparel, Piece Goods, and Notions Merchant Wholesalers",
  "Grocery and Related Product Merchant Wholesalers",
  "Farm Product Raw Material Merchant Wholesalers",
  "Chemical and Allied Products Merchant Wholesalers",
  "Petroleum and Petroleum Products Merchant Wholesalers",
  "Beer, Wine, and Distilled Alcoholic Beverage Merchant Wholesalers",
  "Miscellaneous Nondurable Goods Merchant Wholesalers",
  "Wholesale Trade Agents and Brokers",
  "Retail Trade",
  "Automobile Dealers",
  "Other Motor Vehicle Dealers",
  "Automotive Parts, Accessories, and Tire Retailers",
  "Building Material and Supplies Dealers",
  "Lawn and Garden Equipment and Supplies Retailers",
  "Grocery and Convenience Retailers",
  "Specialty Food Retailers",
  "Beer, Wine, and Liquor Retailers",
  "Furniture and Home Furnishings Retailers",
  "Electronics and Appliance Retailers",
  "Health and Personal Care Retailers",
  "Gasoline Stations",
  "Clothing and Clothing Accessories Retailers",
  "Shoe Retailers",
  "Jewelry, Luggage, and Leather Goods Retailers",
  "Sporting Goods, Hobby, and Musical Instrument Retailers",
  "Book Retailers and News Dealers",
  "Department Stores",
  "General Merchandise Retailers, including Warehouse Clubs and Supercenters",
  "Florists",
  "Office Supplies, Stationery, and Gift Retailers",
  "Used Merchandise Retailers",
  "Other Miscellaneous Retailers",
  "Nonstore Retailers",
  "Transportation and Warehousing",
  "Scheduled Air Transportation",
  "Nonscheduled Air Transportation",
  "Rail Transportation",
  "Deep Sea, Coastal, and Great Lakes Water Transportation",
  "Inland Water Transportation",
  "General Freight Trucking",
  "Specialized Freight Trucking",
  "Urban Transit Systems",
  "Interurban and Rural Bus Transportation",
  "Taxi and Limousine Service",
  "School and Employee Bus Transportation",
  "Charter Bus Industry",
  "Other Transit and Ground Passenger Transportation",
  "Pipeline Transportation of Crude Oil",
  "Pipeline Transportation of Natural Gas",
  "Other Pipeline Transportation",
  "Scenic and Sightseeing Transportation, Land",
  "Scenic and Sightseeing Transportation, Water",
  "Scenic and Sightseeing Transportation, Other",
  "Support Activities for Air Transportation",
  "Support Activities for Rail Transportation",
  "Support Activities for Water Transportation",
  "Support Activities for Road Transportation",
  "Freight Transportation Arrangement",
  "Other Support Activities for Transportation",
  "Postal Service",
  "Couriers and Express Delivery Services",
  "Local Messengers and Local Delivery",
  "Warehousing and Storage",
  "Information",
  "Newspaper, Periodical, Book, and Directory Publishers",
  "Software Publishers",
  "Motion Picture and Video Industries",
  "Sound Recording Industries",
  "Radio and Television Broadcasting",
  "Cable and Other Subscription Programming",
  "Wired and Wireless Telecommunications Carriers",
  "Satellite Telecommunications",
  "Other Telecommunications",
  "Computing Infrastructure Providers, Data Processing, Web Hosting, and Related Services",
  "Web Search Portals, Libraries, Archives, and Other Information Services",
  "Media Streaming Distribution Services, Social Networks, and Other Media Networks and Content Providers",
  "Finance and Insurance",
  "Monetary Authorities-Central Bank",
  "Credit Intermediation and Related Activities",
  "Commercial Banking",
  "Savings Institutions",
  "Credit Unions",
  "Other Depository Credit Intermediation",
  "Credit Card Issuing",
  "Sales Financing",
  "Other Nondepository Credit Intermediation",
  "Activities Related to Credit Intermediation",
  "Securities and Commodity Contracts Intermediation and Brokerage",
  "Securities and Commodity Exchanges",
  "Other Financial Investment Activities",
  "Insurance Carriers",
  "Agencies, Brokerages, and Other Insurance Related Activities",
  "Insurance and Employee Benefit Funds",
  "Other Investment Pools and Funds",
  "Real Estate and Rental and Leasing",
  "Lessors of Real Estate",
  "Offices of Real Estate Agents and Brokers",
  "Activities Related to Real Estate",
  "Automotive Equipment Rental and Leasing",
  "Consumer Goods Rental",
  "General Rental Centers",
  "Commercial and Industrial Machinery and Equipment Rental and Leasing",
  "Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)",
  "Professional, Scientific, and Technical Services",
  "Legal Services",
  "Accounting, Tax Preparation, Bookkeeping, and Payroll Services",
  "Architectural, Engineering, and Related Services",
  "Specialized Design Services",
  "Computer Systems Design and Related Services",
  "Management, Scientific, and Technical Consulting Services",
  "Scientific Research and Development Services",
  "Advertising, Public Relations, and Related Services",
  "Other Professional, Scientific, and Technical Services",
  "Management of Companies and Enterprises",
  "Administrative and Support and Waste Management and Remediation Services",
  "Office Administrative Services",
  "Facilities Support Services",
  "Employment Services",
  "Business Support Services",
  "Travel Arrangement and Reservation Services",
  "Investigation and Security Services",
  "Services to Buildings and Dwellings",
  "Other Support Services",
  "Waste Collection",
  "Waste Treatment and Disposal",
  "Remediation and Other Waste Management Services",
  "Educational Services",
  "Elementary and Secondary Schools",
  "Junior Colleges",
  "Colleges, Universities, and Professional Schools",
  "Business Schools and Computer and Management Training",
  "Technical and Trade Schools",
  "Other Schools and Instruction",
  "Educational Support Services",
  "Health Care and Social Assistance",
  "Offices of Physicians",
  "Offices of Dentists",
  "Offices of Other Health Practitioners",
  "Outpatient Care Centers",
  "Medical and Diagnostic Laboratories",
  "Home Health Care Services",
  "Other Ambulatory Health Care Services",
  "General Medical and Surgical Hospitals",
  "Psychiatric and Substance Abuse Hospitals",
  "Specialty (except Psychiatric and Substance Abuse) Hospitals",
  "Nursing Care Facilities (Skilled Nursing Facilities)",
  "Residential Intellectual and Developmental Disability, Mental Health, and Substance Abuse Facilities",
  "Continuing Care Retirement Communities and Assisted Living Facilities for the Elderly",
  "Other Residential Care Facilities",
  "Individual and Family Services",
  "Community Food and Housing, and Emergency and Other Relief Services",
  "Vocational Rehabilitation Services",
  "Child Care Services",
  "Arts, Entertainment, and Recreation",
  "Performing Arts Companies",
  "Spectator Sports",
  "Promoters of Performing Arts, Sports, and Similar Events",
  "Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures",
  "Independent Artists, Writers, and Performers",
  "Museums, Historical Sites, and Similar Institutions",
  "Amusement Parks and Arcades",
  "Gambling Industries",
  "Other Amusement and Recreation Industries",
  "Accommodation and Food Services",
  "Traveler Accommodation",
  "RV (Recreational Vehicle) Parks and Recreational Camps",
  "Rooming and Boarding Houses, Dormitories, and Workers' Camps",
  "Special Food Services",
  "Drinking Places (Alcoholic Beverages)",
  "Restaurants and Other Eating Places",
  "Other Services (except Public Administration)",
  "Automotive Repair and Maintenance",
  "Electronic and Precision Equipment Repair and Maintenance",
  "Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance",
  "Personal and Household Goods Repair and Maintenance",
  "Personal Care Services",
  "Death Care Services",
  "Drycleaning and Laundry Services",
  "Other Personal Services",
  "Religious Organizations",
  "Grantmaking and Giving Services",
  "Social Advocacy Organizations",
  "Civic and Social Organizations",
  "Business, Professional, Labor, Political, and Similar Organizations",
  "Private Households",
  "Public Administration",
  "Executive, Legislative, and Other General Government Support",
  "Justice, Public Order, and Safety Activities",
  "Administration of Human Resource Programs",
  "Administration of Environmental Quality Programs",
  "Administration of Housing Programs, Urban Planning, and Community Development",
  "Administration of Economic Programs",
  "Space Research and Technology",
  "National Security and International Affairs",
] as const;

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function industryMatches(name: string, needle: string): boolean {
  const hay = name.toLowerCase();
  if (hay === needle || hay.startsWith(needle)) return true;
  if (needle.length <= 2) {
    return new RegExp(`(^|[^a-z0-9])${escapeRegExp(needle)}`).test(hay);
  }
  return hay.includes(needle);
}

export function searchUsIndustries(query: string): string[] {
  const needle = query.trim().toLowerCase();
  const company = [...companyIndustries];
  const census = [...usIndustries];
  if (!needle) return [...company, ...census];
  return [
    ...company.filter((name) => industryMatches(name, needle)),
    ...census.filter((name) => industryMatches(name, needle)),
  ];
}

export function findUsIndustry(query: string): string | null {
  const needle = query.trim().toLowerCase();
  if (!needle) return null;
  return (
    companyIndustries.find((name) => name.toLowerCase() === needle) ??
    usIndustries.find((name) => name.toLowerCase() === needle) ??
    null
  );
}
